### ISSUE TITLE
Question on the difference between the definition of length and width

### ISSUE THREAD

**Issue by PPatrickGU** [OneOneLiu/ggcnn_cornell_dataset#7]
Hello, when comparing your code with that of dougsm [https://github.com/dougsm/ggcnn](url), I found that both of you predict width instead of length.

As you've mentioned in your code, the definition of length and width is different in your code from that of dougsm. Did he make a mistake？This question also bothers me a long time.

**Comment by PPatrickGU** [comment]
I can fully understand your choice of predicting the width (the gripper should open), but I can't understand Dougsm

**Comment by OneOneLiu** [comment]
I'm so sorry to hear that, when I first read the original GGCNN code, I also feel weird about the name of the variable of `length` and `width`, I think the name `width` is more suitable to represent the open width of the gripper, that's why I changed it during my study, but this is just a little naming niggle, no one's made a mistake, just do it the way you like. Hope this helps.

**Comment by PPatrickGU** [comment]
Thanks :)

**Comment by PPatrickGU** [comment]
Thanks :)
